apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: example
  namespace: default
spec:
  ingressClassName: nginx
  rules:
    - host: minikube
      http:
        paths:
          - backend:
              service:
                name: httpenv
                port:
                  number: 8888
            path: /
            pathType: Prefix